manifest:
  remotes:
    - name: ergohaven
      url-base: https://github.com/ergohaven
    - name: zzeneg
      url-base: https://github.com/zzeneg
    - name: urob
      url-base: https://github.com/urob
  projects:
    - name: ergohaven-zmk
      remote: ergohaven
      revision: main
      import: config/west.yml
    - name: zmk-raw-hid
      remote: zzeneg
      revision: main
  self:
    path: config
